env:
  es6: true
  node: true
  jest: true
extends:
  - standard
  - "eslint:recommended"
overrides:
  [
    {
      files: ["*.ts", "*.tsx"],
      rules: { "@typescript-eslint/no-unused-vars": [2, { args: "none" }] },
    },
  ]
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - "@typescript-eslint"
rules: { 
  space-before-function-paren: 0,
  indent: ["error", 4]
 }
