name: Pull Request
on: pull_request
jobs:
  test:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x, 24.x]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install npm
      run: npm install
    - name: Run build
      run: npm run build --if-present
    - name: Run tests
      run: npm test
    - name: Run lint
      run: npm run lint
